# -*- coding: utf-8 -*-
"""ExDoisPythonPasswordVerify.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lLLrtAbpPoirkquTPu4xALazpowHA85X
"""

# Senha universal do sistema
senha_correta = "admin123"


# -----------------------------------------
# FUNÇÃO PARA MOSTRAR OS ALUNOS
# -----------------------------------------

def mostrar_alunos():

    alunos = [
        {
            "id": 1,
            "nome": "João Silva",
            "idade": 20,
            "ra": "2026001",
            "curso": "Análise e Desenvolvimento de Sistemas",
            "email": "joao@email.com",
            "nota1": 8.0,
            "nota2": 7.0
        },
        {
            "id": 2,
            "nome": "Maria Souza",
            "idade": 21,
            "ra": "2026002",
            "curso": "Administração",
            "email": "maria@email.com",
            "nota1": 9.0,
            "nota2": 8.5
        },
        {
            "id": 3,
            "nome": "Carlos Oliveira",
            "idade": 22,
            "ra": "2026003",
            "curso": "Engenharia de Software",
            "email": "carlos@email.com",
            "nota1": 5.0,
            "nota2": 6.0
        },
        {
            "id": 4,
            "nome": "Ana Santos",
            "idade": 19,
            "ra": "2026004",
            "curso": "Ciência da Computação",
            "email": "ana@email.com",
            "nota1": 7.5,
            "nota2": 8.0
        },
        {
            "id": 5,
            "nome": "Pedro Costa",
            "idade": 23,
            "ra": "2026005",
            "curso": "Sistemas de Informação",
            "email": "pedro@email.com",
            "nota1": 4.0,
            "nota2": 5.0
        }
    ]

    print("\n========================================")
    print("          ÁREA ADMINISTRATIVA")
    print("========================================")

    for aluno in alunos:

        # Calcula a média
        media = (aluno["nota1"] + aluno["nota2"]) / 2

        # Verifica a situação
        if media >= 6.0:
            situacao = "Aprovado"
        else:
            situacao = "Reprovado"

        # Mostra as informações
        print("\n----------------------------------------")
        print("ID:", aluno["id"])
        print("Nome:", aluno["nome"])
        print("Idade:", aluno["idade"])
        print("RA:", aluno["ra"])
        print("Curso:", aluno["curso"])
        print("E-mail:", aluno["email"])
        print("Nota 1:", aluno["nota1"])
        print("Nota 2:", aluno["nota2"])
        print("Média:", round(media, 2))
        print("Situação:", situacao)


# -----------------------------------------
# FUNÇÃO PARA VERIFICAR A SENHA
# -----------------------------------------

def verificar_senha():
    while True:
        senha = input("\nDigite a senha de acesso: ")
        if senha == senha_correta:
            print("\nSenha correta!")
            print("Acesso autorizado.")
            # Mostra os alunos
            mostrar_alunos()
        else:
            print("\nSenha incorreta!")
            print("Acesso negado.")
            print("Tente novamente.")


# -----------------------------------------
# PROGRAMA PRINCIPAL
# -----------------------------------------

verificar_senha()